# Generated by Django 3.1.4 on 2020-12-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=600, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Palancas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=600, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('valor', models.IntegerField()),
                ('objetivoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.objetivos')),
            ],
        ),
        migrations.CreateModel(
            name='Experimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=600, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('valor', models.IntegerField()),
                ('PalancaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.palancas')),
            ],
        ),
    ]
