# Generated by Django 3.1.4 on 2020-12-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201228_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='titulo',
        ),
    ]
